---
- name: Deploy and Install simple-node-health
  hosts: all  # Replace with your target host group if necessary
  become: yes  # Escalate privileges to run tasks as root
  tasks:
    - name: Copy the simple-node-health .deb package to the target machine
      copy:
        src: /path/to/simple-node-health_1.0.1_amd64.deb
        dest: /tmp/simple-node-health_1.0.1_amd64.deb
        mode: '0644'

    - name: Install simple-node-health package
      ansible.builtin.apt:
        deb: /tmp/simple-node-health_1.0.1_amd64.deb
      register: dpkg_install
      ignore_errors: yes

    - name: Fix broken dependencies if any
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
      loop: "{{ dpkg_install.msg.split() }}"
      when: dpkg_install is failed

    - name: Install simple-node-health package again if needed
      ansible.builtin.apt:
        deb: /tmp/simple-node-health_1.0.1_amd64.deb
      when: dpkg_install is failed

    - name: Ensure snh.service is enabled and started
      ansible.builtin.systemd:
        name: snh.service
        enabled: yes
        state: started