#!/bin/bash
set -e

# Ensure the script is running with root privileges
if [ "$(id -u)" -ne 0 ]; then
  echo "This package must be installed as root. Please run 'sudo dpkg -i <package_name>.deb'."
  exit 1
fi

# Enable and start the service
systemctl daemon-reload
systemctl enable snh.service
systemctl start snh.service

exit 0