#!/bin/bash
set -e

# Ensure the script is running with root privileges
if [ "$(id -u)" -ne 0 ]; then
  echo "This package must be installed as root. Please run 'sudo dpkg -i <package_name>.deb'."
  exit 1
fi

adduser --system --no-create-home --group snh

touch /var/log/snh.log
chown snh:snh /var/log/snh.log

#Adding system user `snh' (UID 117) ...
#Adding new group `snh' (GID 120) ...
#Adding new user `snh' (UID 117) with group `snh' ...
#Not creating home directory `/home/snh'.

# Enable and start the service
systemctl daemon-reload
systemctl enable snh.service
systemctl start snh.service

exit 0